image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install

ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    main: true

vscode:
  extensions:
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
    - orta.vscode-jest
    - esbenp.prettier-vscode
    - steoates.autoimport
