version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  nats:
    image: nats:latest
    ports:
      - 4222:4222
  dozzle:
    image: amir20/dozzle:latest
    command: "--filter label=yifan"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
