version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  nats:
    image: nats:latest
    ports:
      - 4222:4222
