name: Continuous Deployment

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  pre-deploy:
    name: ⚙️ Configure
    runs-on: ubuntu-latest
    steps:
      - name: app:create
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            apps:create ${{ github.event.repository.name }}
      - name: docker-options:add
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker-options:add ${{ github.event.repository.name }} deploy "-v /var/run/docker.sock:/var/run/docker.sock"
      - name: nats:linked
        continue-on-error: true
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            nats:linked ${{ secrets.NATS_SERVICE }} ${{ github.event.repository.name }}
      - name: nats:link
        if: ${{ failure() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            nats:link ${{ secrets.NATS_SERVICE }} ${{ github.event.repository.name }}

  deploy:
    name: 🚀 Deploy
    needs: pre-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}/${{ github.event.repository.name }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

  post-deploy:
    name: 🔐 SSL
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: letsencrypt:auto-renew
        continue-on-error: true
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            letsencrypt:list | grep -q ${{ github.event.repository.name }}
      - name: letsencrypt:enable
        if: ${{ failure() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            letsencrypt:enable ${{ github.event.repository.name }}
